import type { Config } from "tailwindcss";

// Tokens extracted verbatim from the Stitch ZIP (all 11 screens shared this
// exact palette/scale). Single source of truth — do not redefine these
// values anywhere else in the codebase.
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c9c4d7",
        "on-primary": "#30009a",
        "on-primary-container": "#d8ceff",
        "tertiary-container": "#5c5b5b",
        primary: "#cabeff",
        "secondary-fixed": "#e5e2e1",
        "secondary-container": "#4a4949",
        "surface-container-high": "#282a2b",
        "on-surface": "#e2e2e2",
        "on-tertiary": "#313030",
        "outline-variant": "#484554",
        surface: "#121414",
        "surface-tint": "#cabeff",
        "surface-container-highest": "#333535",
        "surface-container-lowest": "#0c0f0f",
        "primary-container": "#5d3fd3",
        error: "#ffb4ab",
        "surface-dim": "#121414",
        "on-error": "#690005",
        "primary-fixed": "#e6deff",
        "surface-bright": "#38393a",
        outline: "#938ea0",
        "inverse-primary": "#6042d6",
        "on-tertiary-container": "#d6d3d3",
        "on-secondary-fixed-variant": "#474646",
        "surface-variant": "#333535",
        secondary: "#c9c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "tertiary-fixed": "#e5e2e1",
        background: "#121414",
        "surface-container-low": "#1a1c1c",
        tertiary: "#c8c6c5",
        "primary-fixed-dim": "#cabeff",
        "on-background": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary-fixed": "#1c0062",
        "on-primary-fixed-variant": "#4723be",
        "on-secondary-container": "#bab8b7",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary": "#313030",
        "secondary-fixed-dim": "#c9c6c5",
        "surface-container": "#1e2020",
        "on-secondary-fixed": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2f3131",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        md: "24px",
        base: "8px",
        sm: "12px",
        xs: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "display-hero": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-hero-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
